version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/MCPM"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/Jarvis"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/mcpm_source"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
